model_cfg: edgetam.yaml
seed: 2026
classification_frame: 50
tracker:
  box_association_iou: 0.05
box_source: mask
frames_fps: 5
mask_generator:
  points_per_side: 32
  pred_iou_thresh: 0.8
  stability_score_thresh: 0.85
  min_mask_region_area: 200
anchors:
  candidate_min_area: 800
  candidate_max_area: 100000
  initial_positive_points: 22
  history_length: 20
  tracking_points: 10
  min_valid_points: 5
  track_mask_threshold: 0.0
